version: 2.1

parameters:
  app1:
    type: boolean
    default: ""

executors:
  base:
    docker:
      - image: cimg/base:stable
    resource_class: small

filter: &filter >-
  <<
  pipeline.parameters.app1
  >>

jobs:

  tests-done:
    executor: base
    steps:
      - run: echo "DONE"

  build-app1:
    executor: base
    steps:
      - run: echo "DONE"

workflows:
  version: 2

  acp:
    jobs:
      - build-app1: 
          run-job: *filter
      - tests-done: 
          run-job: *filter
          requires:
            - build-app1
