version: 2.1
#test
orbs:
  docker: circleci/docker@1.5.0
  circletron: circletron/circletron@3.0.5
#hehehe
parameters:
  app2:
    type: boolean
    default: false



jobs:
  app2-job:
    docker:
      # next-gen ubuntu image with java 11.0.10
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo app2 test!"
      - run:
          name: "sleep"
          command: "sleep 60"



workflows:
  app2:
    jobs:
      - app2-job



